language: python 
python: '2.7'  
script:
  - pip install -r requirements.txt 
  - coverage run tests.py
after_success: 
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then zappa update; fi
notifications:
  email: scottx611x@gmail.com
  on_success: never
